/** Contenido científico independiente del dibujo y de los controles. */
export const sources = {
  bodyparts: { title: 'BodyParts3D / Anatomography · Mallas óseas T2–T4', institution: 'Database Center for Life Science (DBCLS). Versión 4.3, CC BY-SA 2.1 Japan. Mitsuhashi et al. (2009), DOI: 10.1093/nar/gkn613.', url: 'https://lifesciencedb.jp/bp3d/info_en/index.html' },
  vertebra: { title: 'OpenStax · La columna vertebral', institution: 'Anatomy and Physiology 2e, sección 7.3', url: 'https://openstax.org/books/anatomy-and-physiology-2e/pages/7-3-the-vertebral-column' },
  columns: { title: 'University of Wisconsin · Spinal cord', institution: 'Material docente de neuroanatomía, organización de los cordones y vías medulares', url: 'https://www.neuroanatomy.wisc.edu/coursebook/webcord.pdf' },
  morphology: { title: 'NCBI Bookshelf · Spinal Cord Morphology', institution: 'StatPearls, revisión anatómica de la médula espinal', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545206/' },
  spinothalamic: { title: 'UTHealth · Vías espinotalámicas', institution: 'Neuroanatomy Online, laboratorio 3', url: 'https://nba.uth.tmc.edu/neuroanatomy/L3/Lab03p02_index.html' },
  cerebellar: { title: 'UTHealth · Vías espinocerebelosas', institution: 'Neuroanatomy Online, laboratorio 3', url: 'https://nba.uth.tmc.edu/neuroanatomy/L3/Lab03p16_index.html' },
  dorsal: { title: 'NCBI Bookshelf · Spinocerebellar Dorsal Tract', institution: 'Koh y Markovich, StatPearls', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556013/' },
  cortex: { title: 'Duke University · Vías corticoespinales', institution: 'Neurosciences Learning Resources, apéndice 3', url: 'https://brain.oit.duke.edu/appendix03/appendix03.html' },
  motor: { title: 'UTHealth · Vías motoras descendentes', institution: 'Neuroscience Online, sección 3, capítulo 2', url: 'https://nba.uth.tmc.edu/neuroscience/m/s3/chapter02.html' },
  reticular: { title: 'UTHealth · Vías reticuloespinales', institution: 'Neuroanatomy Online, laboratorio 6', url: 'https://nba.uth.tmc.edu/neuroanatomy/L6/Lab06p22_index.html' },
  clinical: { title: 'University of Wisconsin · Clínica medular', institution: 'Material docente sobre lesiones medulares y radiculopatías', url: 'https://www.neuroanatomy.wisc.edu/coursebook/clinicalspinal.pdf' },
  research: { title: 'Vedantam et al. (2019) · Organización espinotalámica cervical', institution: 'Neurosurgery 84(6), E311–E317. DOI: 10.1093/neuros/nyy330', url: 'https://pubmed.ncbi.nlm.nih.gov/30011044/' },
  internal: { title: 'UTHealth · Organización interna de la médula', institution: 'Neuroscience Online, sección 2, capítulo 3', url: 'https://nba.uth.tmc.edu/neuroscience/m/s2/chapter03.html' },
  meninges: { title: 'NCBI Bookshelf · Meninges espinales', institution: 'StatPearls, Anatomy, Back, Spinal Meninges', url: 'https://www.ncbi.nlm.nih.gov/books/NBK547755/' }
};

// Cada vía tiene un área bilateral en el SVG. Las fronteras son didácticas.
export const tracts = [
  { id:'gracilis', short:'Fascículo grácil', name:'Fascículo grácil', latin:'Fasciculus gracilis', code:'G', direction:'ascending', color:'#488f80',
    summary:'Lleva información de vibración, tacto discriminativo y posición consciente del miembro inferior y del tronco inferior.',
    anatomy:'Porción medial del cordón posterior. Está presente a lo largo de la médula.',
    route:['Ganglio de la raíz dorsal','Núcleo grácil (bulbo)','Tálamo VPL → corteza somatosensorial'],
    crossing:'Asciende del mismo lado en la médula. Cruza en el bulbo como fibras arcuatas internas y continúa por el lemnisco medial.',
    function:'Ayuda a reconocer la posición de una pierna sin verla y a distinguir estímulos táctiles finos.',
    clinical:'Una lesión medular unilateral puede reducir estas modalidades del mismo lado por debajo de la lesión y causar ataxia sensitiva.', sources:['columns','clinical'],
    path:'M 310 120 Q 332 119 352 128 L 330 177 Q 318 205 310 246 Z', label:[327,148] },
  { id:'cuneatus', short:'Fascículo cuneiforme', name:'Fascículo cuneiforme', latin:'Fasciculus cuneatus', code:'C', direction:'ascending', color:'#74a99a',
    summary:'Transporta tacto discriminativo, vibración y propiocepción consciente del miembro superior y del tronco superior.',
    anatomy:'Lateral al fascículo grácil en el cordón posterior. Aparece aproximadamente desde T6 hacia niveles más rostrales.',
    route:['Ganglio de la raíz dorsal','Núcleo cuneiforme (bulbo)','Tálamo VPL → corteza somatosensorial'],
    crossing:'Permanece del mismo lado durante su recorrido medular. La decusación ocurre en el bulbo.',
    function:'Informa sobre la posición de la mano y permite discriminar características de lo que toca.',
    clinical:'Una lesión por encima de las entradas correspondientes afecta estas modalidades del mismo lado. Una lesión en T3 no interrumpe las aferencias que entran por encima, como las de la mano.', sources:['columns','morphology'],
    path:'M 354 129 Q 375 134 394 150 L 368 193 L 346 207 L 333 179 Z', label:[365,156] },
  { id:'cst-lateral', short:'Corticoespinal lateral', name:'Tracto corticoespinal lateral', latin:'Tractus corticospinalis lateralis', code:'CL', direction:'descending', color:'#c08b56',
    summary:'Conduce órdenes corticales para el movimiento voluntario, especialmente el control preciso de las extremidades.',
    anatomy:'Cordón lateral, por delante del espinocerebeloso posterior. Sus fibras ya cruzaron en el bulbo.',
    route:['Corteza → cápsula interna','Pirámides del bulbo → decusación','Interneuronas y motoneuronas medulares'],
    crossing:'La mayoría cruza en la decusación piramidal del bulbo. Dentro de la médula influye principalmente sobre el mismo lado.',
    function:'La vía completa participa en el control hábil de las extremidades. En este corte T3 pasan fibras dirigidas a segmentos inferiores.',
    clinical:'Una lesión medular puede causar debilidad del mismo lado por debajo del daño, con signos de neurona motora superior que evolucionan con el tiempo.', sources:['cortex','clinical'],
    path:'M 381 187 Q 407 181 434 202 Q 444 218 441 239 L 402 242 L 377 221 Z', label:[413,218] },
  { id:'cst-anterior', short:'Corticoespinal anterior', name:'Tracto corticoespinal anterior', latin:'Tractus corticospinalis anterior', code:'CA', direction:'descending', color:'#d9ab78',
    summary:'Contribuye al control voluntario de la musculatura axial y proximal, con proyecciones frecuentemente bilaterales.',
    anatomy:'Cordón anterior, cerca de la fisura mediana anterior. Su extensión caudal es variable.',
    route:['Corteza motora','Pirámides sin cruce inicial','Circuitos mediales del asta anterior'],
    crossing:'Muchas fibras cruzan cerca de su terminación medular; otras proyectan al mismo lado. La organización es más bilateral que en la vía lateral.',
    function:'Ayuda a coordinar movimientos del tronco y músculos proximales.',
    clinical:'Por su distribución bilateral, un daño aislado unilateral no suele producir el patrón marcado de debilidad distal de una lesión corticoespinal lateral.', sources:['cortex','motor'],
    path:'M 319 311 L 340 319 L 345 368 Q 331 373 315 374 L 315 334 Z', label:[329,349] },
  { id:'stt-lateral', short:'Espinotalámico lateral', name:'Tracto espinotalámico lateral', latin:'Sistema anterolateral', code:'EL', direction:'ascending', color:'#337a77',
    summary:'Forma parte del sistema anterolateral y transmite principalmente información de dolor y temperatura.',
    anatomy:'Región anterolateral de la sustancia blanca. La separación de modalidades y sus fronteras no es absoluta.',
    route:['Ganglio dorsal → asta posterior','Comisura blanca anterior → lado opuesto','Tálamo → redes corticales'],
    crossing:'Cruza en la médula, por la comisura blanca anterior, cerca del nivel de entrada. Las aferencias pueden recorrer uno o dos segmentos antes del relevo.',
    function:'Permite detectar estímulos dolorosos y cambios de temperatura.',
    clinical:'Una lesión unilateral puede disminuir dolor y temperatura del lado opuesto, típicamente comenzando uno o dos segmentos por debajo.', sources:['spinothalamic','morphology','research'],
    path:'M 407 257 L 442 252 Q 449 269 439 294 L 419 313 L 396 290 Z', label:[424,281] },
  { id:'stt-anterior', short:'Espinotalámico anterior', name:'Tracto espinotalámico anterior', latin:'Sistema anterolateral', code:'EA', direction:'ascending', color:'#68a09a',
    summary:'Tradicionalmente se asocia con tacto poco discriminativo y presión dentro del sistema anterolateral.',
    anatomy:'Área anterior y anterolateral. Se dibuja separada para aprender, aunque las modalidades y fibras se solapan.',
    route:['Aferencias cutáneas → asta posterior','Proyecciones medulares cruzadas','Tálamo → corteza'],
    crossing:'Muchas fibras cruzan por la comisura blanca anterior. Existen proyecciones y rutas redundantes para el tacto.',
    function:'Contribuye a percibir contacto y presión sin el detalle espacial que aportan los cordones posteriores.',
    clinical:'Una lesión aislada no suele eliminar todo el tacto: otras vías también transmiten información táctil.', sources:['morphology','research'],
    path:'M 360 335 L 382 323 L 403 333 Q 388 355 353 366 Z', label:[376,346] },
  { id:'sct-posterior', short:'Espinocerebeloso posterior', name:'Tracto espinocerebeloso posterior', latin:'Tractus spinocerebellaris posterior', code:'EP', direction:'ascending', color:'#8cb8a0',
    summary:'Lleva al cerebelo propiocepción no consciente del tronco y miembro inferior.',
    anatomy:'Borde dorsolateral de la médula, superficial al corticoespinal lateral. Se origina principalmente en el núcleo de Clarke.',
    route:['Propioceptores → ganglio dorsal','Núcleo de Clarke → ascenso ipsilateral','Pedúnculo cerebeloso inferior'],
    crossing:'No presenta una decusación principal. La información termina en el cerebelo del mismo lado.',
    function:'Informa sobre la posición y el estado mecánico de los músculos para ajustar la coordinación.',
    clinical:'Su alteración puede contribuir a ataxia del mismo lado. No es equivalente a perder propiocepción consciente.', sources:['dorsal','cerebellar'],
    path:'M 398 150 Q 441 173 453 222 L 441 221 Q 432 184 393 174 Z', label:[430,179] },
  { id:'sct-anterior', short:'Espinocerebeloso anterior', name:'Tracto espinocerebeloso anterior', latin:'Tractus spinocerebellaris anterior', code:'EV', direction:'ascending', color:'#a9c5ad',
    summary:'Informa al cerebelo sobre la actividad de circuitos espinales implicados en el movimiento de los miembros inferiores.',
    anatomy:'Periferia ventrolateral del cordón lateral. No transporta únicamente información directa de receptores musculares.',
    route:['Circuitos espinales lumbosacros','Ascenso principalmente contralateral','Pedúnculo cerebeloso superior'],
    crossing:'Muchas fibras cruzan primero en la médula y vuelven a cruzar en el cerebelo, manteniendo una representación funcional del lado de origen.',
    function:'Contribuye a comparar y coordinar la actividad de redes espinales durante el movimiento.',
    clinical:'Una lesión puede alterar la coordinación. La regla del doble cruce es una simplificación de una organización más compleja.', sources:['cerebellar'],
    path:'M 445 293 L 457 275 Q 451 328 418 349 L 412 336 Q 434 319 445 293 Z', label:[440,317] },
  { id:'vestibulo', short:'Vestibuloespinal lateral', name:'Tracto vestibuloespinal lateral', latin:'Tractus vestibulospinalis lateralis', code:'VL', direction:'descending', color:'#b99b61',
    summary:'Conecta los núcleos vestibulares con circuitos medulares que ayudan a mantener el equilibrio y el sostén postural.',
    anatomy:'Cordón anterior y región ventrolateral. Se representa el componente lateral, no toda la familia vestibuloespinal.',
    route:['Núcleo vestibular lateral','Descenso principalmente ipsilateral','Circuitos de músculos antigravitatorios'],
    crossing:'El componente lateral desciende principalmente sin cruzarse. El componente medial tiene otra distribución y no se representa aquí.',
    function:'Favorece ajustes de la musculatura extensora frente a cambios de posición y equilibrio.',
    clinical:'Su alteración puede contribuir a inestabilidad postural. Una lesión clínica suele involucrar más de una vía.', sources:['motor'],
    path:'M 365 307 L 385 299 L 405 317 L 382 327 L 356 327 Z', label:[383,316] },
  { id:'reticulo', short:'Vías reticuloespinales', name:'Vías reticuloespinales', latin:'Proyecciones pontinas y bulbares', code:'RE', direction:'descending', color:'#b58c72',
    summary:'Vinculan la formación reticular con redes medulares que regulan postura, tono, movimientos y reflejos.',
    anatomy:'Proyecciones distribuidas en regiones anteriores y laterales. Una sola zona agrupa aquí varios componentes.',
    route:['Formación reticular de puente y bulbo','Proyecciones medulares bilaterales','Interneuronas y circuitos motores'],
    crossing:'No tienen una decusación única. Sus proyecciones incluyen fibras ipsilaterales y bilaterales, según el componente.',
    function:'Participan en ajustes posturales, actividad locomotora y regulación contextual de reflejos.',
    clinical:'Su alteración puede modificar el tono y los ajustes posturales. No es posible atribuir un síntoma específico solo a la zona dibujada.', sources:['reticular'],
    path:'M 382 247 L 404 246 L 405 279 L 389 294 L 371 282 Z', label:[389,268] }
];

export const structures = {
  spinous: {name:'Apófisis espinosa',description:'Proyección ósea posterior del arco vertebral. Sirve como punto de inserción para músculos y ligamentos. No forma parte de la médula.'},
  canal: {name:'Canal vertebral',description:'Espacio formado por la continuidad de los forámenes vertebrales. Aloja la médula, sus cubiertas y otras estructuras. La envolvente turquesa marca este espacio, no una pared anatómica.'},
  cord: {name:'Médula espinal',description:'Tejido del sistema nervioso central situado dentro del canal vertebral. La sustancia gris central está rodeada por sustancia blanca con vías ascendentes y descendentes.'},
  body: {name:'Cuerpo vertebral',description:'Porción anterior de la vértebra que soporta carga. Los discos intervertebrales se sitúan entre cuerpos vecinos. El arco vertebral queda detrás del cuerpo.'},
  arch: {name:'Arco vertebral',description:'Los pedículos y las láminas conectan con el cuerpo vertebral y rodean el foramen vertebral por detrás y a los lados.'},
  transverse: {name:'Apófisis transversa',description:'Proyección lateral del arco vertebral que ofrece inserción para músculos y ligamentos. En las vértebras torácicas también participa en la articulación con las costillas.'},
  articular: {name:'Apófisis articular',description:'Proyección que participa en las articulaciones entre vértebras vecinas. Aquí se representa su volumen de forma simplificada.'},
  disc: {name:'Disco intervertebral',description:'Estructura fibrocartilaginosa situada entre cuerpos vertebrales adyacentes. Contribuye a distribuir cargas y permite movimiento entre vértebras.'}
};

export const questions = [
  {question:'Una lesión medular derecha interrumpe el fascículo grácil. ¿Qué cambio esperas por debajo de la lesión?',options:['Pérdida de vibración y posición consciente a la derecha','Pérdida de dolor y temperatura a la izquierda','Parálisis facial derecha'],correct:0,explanation:'El fascículo grácil todavía no ha cruzado mientras recorre la médula. Su decusación está en el bulbo; por eso el déficit medular es ipsilateral.'},
  {question:'¿Qué tracto se asocia principalmente con dolor y temperatura?',options:['Corticoespinal lateral','Espinotalámico lateral','Fascículo cuneiforme'],correct:1,explanation:'El espinotalámico lateral forma parte del sistema anterolateral. Sus fibras cruzan cerca del nivel medular de entrada.'},
  {question:'¿Dónde cruza la mayoría de las fibras que forman el tracto corticoespinal lateral?',options:['En la comisura blanca anterior de cada segmento','En el cerebelo','En la decusación piramidal del bulbo'],correct:2,explanation:'La mayoría cruza en el bulbo antes de entrar en la médula. Una lesión medular produce por ello debilidad principalmente del mismo lado.'},
  {question:'¿Por qué el corte torácico alto incluye un fascículo cuneiforme?',options:['Porque aparece aproximadamente desde T6 hacia niveles más rostrales','Porque está presente solo en segmentos sacros','Porque contiene los cuerpos celulares de todas las motoneuronas'],correct:0,explanation:'El fascículo cuneiforme lleva información de la parte superior del cuerpo. No se representa en un corte medular torácico bajo o lumbar.'},
  {question:'¿Qué estructura corresponde a las prominencias óseas palpables en la línea media de la espalda?',options:['Los fascículos gráciles','Las apófisis espinosas','El conducto central de la médula'],correct:1,explanation:'Las apófisis espinosas son proyecciones posteriores del arco vertebral y sirven como puntos de inserción muscular y ligamentaria.'},
  {question:'¿Qué vía se asocia con propiocepción no consciente y llega principalmente por el pedúnculo cerebeloso inferior?',options:['Espinocerebeloso posterior','Espinotalámico anterior','Corticoespinal anterior'],correct:0,explanation:'El espinocerebeloso posterior asciende ipsilateralmente y aporta información propioceptiva del tronco y miembro inferior al cerebelo.'},
  {question:'¿Cuál es la diferencia entre el canal vertebral y el conducto central?',options:['Son dos nombres para la misma estructura','El canal está dentro de la médula y el conducto fuera','El canal es un espacio óseo; el conducto central está dentro de la médula'],correct:2,explanation:'El canal vertebral contiene la médula y sus cubiertas. El conducto central es una pequeña luz en el centro de la sustancia gris.'},
  {question:'Si el espinotalámico lateral derecho se daña en la médula, ¿de qué lado se espera el déficit principal de dolor y temperatura por debajo?',options:['Del lado izquierdo, habitualmente desde uno o dos segmentos inferiores','Del lado derecho en todo el cuerpo','Solo en la cara derecha'],correct:0,explanation:'Las fibras ya han cruzado en la médula. La distancia segmentaria depende del recorrido de las aferencias antes del cruce; la cara utiliza otras vías.'}
];
